# Generated by Django 5.1.3 on 2024-12-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.IntegerField(default=0),
        ),
    ]
